sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libnss3
language: node_js
node_js:
  - "9"
install:
  - "yarn install"
test:
  - "yarn test"
notifications:
after_success: 'yarn run coveralls'