language: node_js
dist: trusty
node_js:
  - "9"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "npm install"
test:
  - "npm test"
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  directories:
    - node_modules
# allow headful tests
after_success: 'yarn run coveralls'