sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libnss3
language: node_js
node_js:
  - "9"
install:
  - "npm install"
test:
  - "npm test"
notifications:
after_success: 'npm run coveralls'